apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: expert-labs-root
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/zdmooc/argocd-expert-pack.git
    targetRevision: main
    path: patterns/app-of-apps/children
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
